using Content.Shared._Scp.ScpCCVars;
using Content.Shared._Scp.Shaders.Grain;
using Content.Shared._Scp.Watching.FOV;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ScpTab : Control
{
    public ScpTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        /*
         * Графика
         */

        // Зернистость
        Control.AddOptionCheckBox(ScpCCVars.GrainToggleOverlay, GrainToggleOverlayCheckBox);
        Control.AddOptionSlider(ScpCCVars.GrainStrength, GrainStrengthSlider,
            GrainOverlayComponent.BaseStrengthLimit.Min, GrainOverlayComponent.BaseStrengthLimit.Max);

        // Поле зрения
        Control.AddOptionCheckBox(ScpCCVars.FieldOfViewUseAltMethod, FieldOfViewUseAltMethod);
        Control.AddOptionPercentSlider(ScpCCVars.FieldOfViewOpacity, FieldOfViewOpacitySlider,
            FieldOfViewComponent.MinOpacity, FieldOfViewComponent.MaxOpacity);
        Control.AddOptionPercentSlider(ScpCCVars.FieldOfViewBlurScale, FieldOfViewBlurScale,
            FieldOfViewComponent.MinBlurScale, FieldOfViewComponent.MaxBlurScale);
        Control.AddOptionPercentSlider(ScpCCVars.FieldOfViewCheckCooldown, FieldOfViewCheckCooldown,
            FieldOfViewComponent.MinCooldownCheck, FieldOfViewComponent.MaxCooldownCheck);

        /*
         * Аудио
         */

        // Эхо
        Control.AddOptionCheckBox(ScpCCVars.EchoEnabled, EchoEnabled);
        Control.AddOptionCheckBox(ScpCCVars.EchoStrongPresetPreferred, EchoStrongPresetPreferred);

        // Подавление звуков
        Control.AddOptionCheckBox(ScpCCVars.AudioMufflingEnabled, AudioMufflingEnabled);
        Control.AddOptionCheckBox(ScpCCVars.AudioMufflingHighFrequencyUpdate, AudioMufflingHighFrequencyUpdate);

        Control.Initialize();
    }
}
