using Content.Client._Scp.Shaders.Common.Grain;
using Content.Shared._Scp.ScpCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ScpTab : Control
{
    public ScpTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        /*
         * Графика
         */

        // Зернистость
        Control.AddOptionCheckBox(ScpCCVars.GrainToggleOverlay, GrainToggleOverlayCheckBox);
        Control.AddOptionSlider(ScpCCVars.GrainStrength, GrainStrengthSlider, GrainOverlay.StrengthMin, GrainOverlay.StrengthMax);

        /*
         * Аудио
         */

        // Эхо
        Control.AddOptionCheckBox(ScpCCVars.EchoEnabled, EchoEnabled);
        Control.AddOptionCheckBox(ScpCCVars.EchoStrongPresetPreferred, EchoStrongPresetPreferred);

        // Подавление звуков
        Control.AddOptionCheckBox(ScpCCVars.AudioMufflingEnabled, AudioMufflingEnabled);
        Control.AddOptionCheckBox(ScpCCVars.AudioMufflingHighFrequencyUpdate, AudioMufflingHighFrequencyUpdate);

        Control.Initialize();
    }
}
